const $=(s,c=document)=>c.querySelector(s);const $$=(s,c=document)=>[...c.querySelectorAll(s)];

const mobilePanel=$('#mobile-panel');const menuToggle=$('#menu-toggle');const mobileClose=$('#mobile-close');let menuReturn=null;
function setPageInert(value){$$('.site-header,main,.site-footer').forEach(el=>el.toggleAttribute('inert',value))}
function setMenu(open){if(!mobilePanel)return;mobilePanel.classList.toggle('open',open);mobilePanel.setAttribute('aria-hidden',String(!open));menuToggle?.setAttribute('aria-expanded',String(open));document.body.classList.toggle('no-scroll',open);setPageInert(open);if(open){menuReturn=document.activeElement;mobileClose.focus()}else{menuReturn?.focus()}}
menuToggle?.addEventListener('click',()=>setMenu(true));mobileClose?.addEventListener('click',()=>setMenu(false));
$$('a',mobilePanel).forEach(link=>link.addEventListener('click',()=>{if(!link.hasAttribute('data-modal-trigger'))setMenu(false)}));

const navDrop=$('.nav-drop');const dropButton=navDrop?.querySelector('button');dropButton?.addEventListener('click',()=>{const open=navDrop.classList.toggle('open');dropButton.setAttribute('aria-expanded',String(open))});document.addEventListener('click',e=>{if(navDrop&&!navDrop.contains(e.target)){navDrop.classList.remove('open');dropButton.setAttribute('aria-expanded','false')}});

$$('.faq-button').forEach(button=>button.addEventListener('click',()=>{const expanded=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!expanded));const panel=document.getElementById(button.getAttribute('aria-controls'));panel?.toggleAttribute('data-open',!expanded)}));

const modal=$('#lead-modal');const dialog=modal?.querySelector('[role="dialog"]');const closeModalButton=$('#modal-close');let modalReturn=null;
const focusable='a[href],button:not([disabled]),input:not([disabled]),textarea:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])';
function setFormStartedAt(form){const field=form?.elements.form_started_at;if(field)field.value=String(Math.floor(Date.now()/1000))}
function openModal(trigger){if(!modal)return;const fromMobile=Boolean(trigger.closest('#mobile-panel'));if(mobilePanel?.classList.contains('open'))setMenu(false);modalReturn=fromMobile?menuToggle:trigger;const form=$('#lead-form');form.elements.source_page.value=location.pathname;form.elements.selected_service.value=trigger.dataset.service||'';form.elements.selected_package.value=trigger.dataset.package||'';setFormStartedAt(form);const status=$('.form-status',form);status.textContent='';status.className='form-status';modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('no-scroll');setPageInert(true);setTimeout(()=>form.elements.name.focus(),20)}
function closeModal(){if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('no-scroll');setPageInert(false);modalReturn?.focus()}
$$('[data-modal-trigger]').forEach(t=>t.addEventListener('click',e=>{e.preventDefault();openModal(t)}));closeModalButton?.addEventListener('click',closeModal);modal?.addEventListener('click',e=>{if(e.target.dataset.modalBackdrop!==undefined)closeModal()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(modal?.classList.contains('open'))closeModal();else if(mobilePanel?.classList.contains('open'))setMenu(false);else if(navDrop?.classList.contains('open')){navDrop.classList.remove('open');dropButton.setAttribute('aria-expanded','false');dropButton.focus()}}if(e.key==='Tab'){const scope=modal?.classList.contains('open')?dialog:mobilePanel?.classList.contains('open')?mobilePanel:null;if(scope){const nodes=$$(focusable,scope);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}});

function validateField(field){const value=field.value.trim();let message='';if(field.required&&!value)message='This field is required.';else if(field.type==='email'&&value&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))message='Enter a valid email address.';else if(field.type==='tel'&&value&&!/^[+()\-\s\d]{7,20}$/.test(value))message='Enter a valid phone number.';field.setAttribute('aria-invalid',String(Boolean(message)));const error=document.getElementById(`${field.id}-error`);if(error)error.textContent=message;return !message}
async function submitLeadForm(form){const response=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'},credentials:'same-origin'});const payload=await response.json().catch(()=>({}));if(!response.ok||payload.success!==true)throw new Error(typeof payload.message==='string'&&payload.message?payload.message:'We couldn’t send your request. Please contact our support team directly.');return payload}
$$('form[data-validate]').forEach(form=>{setFormStartedAt(form);const fields=$$('input[required],textarea[required],input[type="email"],input[type="tel"]',form);fields.forEach(f=>f.addEventListener('blur',()=>validateField(f)));form.addEventListener('submit',async e=>{e.preventDefault();if(form.dataset.submitting==='true')return;const valid=fields.map(validateField).every(Boolean);const summary=$('.error-summary',form);const status=$('.form-status',form);status.className='form-status';if(!valid){summary.classList.add('show');summary.focus();return}summary.classList.remove('show');const submit=$('[type="submit"]',form);form.dataset.submitting='true';submit.disabled=true;submit.setAttribute('aria-busy','true');status.textContent='Sending…';status.className='form-status notice show';try{const payload=await submitLeadForm(form);form.reset();form.elements.source_page.value=location.pathname;setFormStartedAt(form);status.textContent=payload.message||'Thank you. Your request has been sent successfully.';status.className='form-status success show';status.focus()}catch(error){status.textContent=error instanceof Error&&error.message?error.message:'We couldn’t send your request. Please contact our support team directly.';status.className='form-status notice show';status.focus()}finally{delete form.dataset.submitting;submit.disabled=false;submit.removeAttribute('aria-busy')}})});

const counters=$$('[data-count-to]');
const reduceMotion=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
if(counters.length){const formatter=new Intl.NumberFormat('en-US');const duration=5000;const statsSection=counters[0].closest('.stats-section');let started=false;let lastScrollY=window.scrollY;counters.forEach(counter=>{counter.textContent='0';counter.dataset.countState='waiting'});const showFinalValues=()=>{counters.forEach(counter=>{counter.textContent=`${formatter.format(Number(counter.dataset.countTo))}${counter.dataset.countSuffix||''}`;counter.dataset.countState='complete'})};const startCounters=()=>{if(started)return;started=true;if(reduceMotion){showFinalValues();return}counters.forEach(counter=>counter.dataset.countState='running');let startTime=null;const update=now=>{if(startTime===null)startTime=now;const progress=Math.min((now-startTime)/duration,1);counters.forEach(counter=>{const target=Number(counter.dataset.countTo);counter.textContent=`${formatter.format(Math.round(target*progress))}${counter.dataset.countSuffix||''}`});if(progress<1)requestAnimationFrame(update);else counters.forEach(counter=>counter.dataset.countState='complete')};requestAnimationFrame(update)};const revealStats=()=>{if(started)return;statsSection.classList.add('is-visible');window.removeEventListener('scroll',onStatsScroll);startCounters()};function onStatsScroll(){const currentScrollY=window.scrollY;const scrollingDown=currentScrollY>lastScrollY;lastScrollY=currentScrollY;if(!scrollingDown)return;const bounds=statsSection.getBoundingClientRect();if(bounds.top<window.innerHeight&&bounds.bottom>0)revealStats()}window.addEventListener('scroll',onStatsScroll,{passive:true})}

$$('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());

const revealGroups=['.grid-2','.grid-3','.pricing-grid','.process','.feature-list','.faq-list','.footer-grid'];
revealGroups.forEach(selector=>$$(selector).forEach(group=>[...group.children].forEach((item,index)=>{item.classList.add('reveal');item.style.setProperty('--reveal-delay',`${Math.min(index,5)*70}ms`)})));
$$('.split').forEach(group=>[...group.children].forEach((item,index)=>{item.classList.add('reveal');item.style.setProperty('--reveal-delay',`${index*90}ms`)}));
const observer='IntersectionObserver'in window?new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -32px'}):null;
$$('.reveal').forEach(el=>observer?observer.observe(el):el.classList.add('visible'));
