(() => {
  const modal = document.getElementById('lead-modal'); if (!modal) return; const dialog = modal.querySelector('[role="dialog"]'), close = document.getElementById('modal-close'); let returnFocus;
  const focusable = 'a[href],button:not([disabled]),input:not([disabled]),textarea:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])';
  const setInert = (value) => document.querySelectorAll('.site-header,main,.site-footer').forEach((element) => element.toggleAttribute('inert', value));
  const open = (trigger) => { const mobilePanel = document.getElementById('mobile-panel'), menuToggle = document.getElementById('menu-toggle'); const fromMobile = Boolean(trigger.closest('#mobile-panel')); if (mobilePanel?.classList.contains('open')) { mobilePanel.classList.remove('open'); mobilePanel.setAttribute('aria-hidden', 'true'); menuToggle?.setAttribute('aria-expanded', 'false'); } returnFocus = fromMobile ? menuToggle : trigger; const form = document.getElementById('lead-form'); form.elements.source_page.value = location.pathname; form.elements.selected_service.value = trigger.dataset.service || ''; form.elements.selected_package.value = trigger.dataset.package || ''; modal.classList.add('open'); modal.setAttribute('aria-hidden', 'false'); document.body.classList.add('no-scroll'); setInert(true); requestAnimationFrame(() => modal.classList.add('is-visible')); setTimeout(() => form.elements.name.focus(), 180); };
  const dismiss = () => { modal.classList.remove('is-visible'); setTimeout(() => { modal.classList.remove('open'); modal.setAttribute('aria-hidden', 'true'); document.body.classList.remove('no-scroll'); setInert(false); returnFocus?.focus(); }, 180); };
  document.querySelectorAll('[data-modal-trigger]').forEach((trigger) => trigger.addEventListener('click', (event) => { event.preventDefault(); open(trigger); })); close?.addEventListener('click', dismiss); modal.addEventListener('click', (event) => { if (event.target.hasAttribute('data-modal-backdrop')) dismiss(); });
  document.addEventListener('keydown', (event) => { if (!modal.classList.contains('open')) return; if (event.key === 'Escape') { dismiss(); return; } if (event.key !== 'Tab') return; const nodes = [...dialog.querySelectorAll(focusable)], first = nodes[0], last = nodes[nodes.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } });
})();
