import { mkdir, rm, cp, writeFile, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';

const root=process.cwd();const out=path.join(root,'dist');
if(process.argv.includes('--clean')){await rm(out,{recursive:true,force:true});process.exit(0)}
await rm(out,{recursive:true,force:true});
for(const dir of ['css','js','assets/images','assets/logo','assets/fonts'])await mkdir(path.join(out,dir),{recursive:true});
await cp(path.join(root,'js'),path.join(out,'js'),{recursive:true});
await cp(path.join(root,'assets'),path.join(out,'assets'),{recursive:true});

const siteUrl='https://markcentralpro.com';
const email='support@markcentralpro.com';const phone='+1 754 547-6430';
const icon=(name)=>{const paths={shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',document:'<path d="M6 2h9l4 4v16H6z"/><path d="M14 2v5h5M9 13h6M9 17h6M9 9h2"/>',globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18"/>',eye:'<path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/>',headset:'<path d="M4 14v-2a8 8 0 0 1 16 0v2M18 19c0 1.7-1.3 3-3 3h-3"/><path d="M4 14h3v5H5a1 1 0 0 1-1-1v-4ZM20 14h-3v5h2a1 1 0 0 0 1-1v-4Z"/>',copyright:'<circle cx="12" cy="12" r="9"/><path d="M15 9.5a4 4 0 1 0 0 5"/>',store:'<path d="M3 10h18M5 10v10h14V10M4 4h16l1 6H3l1-6Z"/><path d="M9 14h6v6"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',check:'<path d="m5 12 4 4L19 6"/>',lock:'<rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>'};return `<svg aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${paths[name]||paths.shield}</svg>`};
const button=(label='Get Started',opts={})=>`<a class="btn ${opts.secondary?'btn-secondary':'btn-primary'}" ${opts.modal!==false?'href="#lead-modal" data-modal-trigger':''}${opts.href?` href="${opts.href}"`:''}${opts.service?` data-service="${opts.service}"`:''}${opts.package?` data-package="${opts.package}"`:''}>${label}${opts.arrow?icon('arrow'):''}</a>`;
const sectionHead=(eyebrow,title,text='')=>`<div class="section-head reveal"><div><p class="eyebrow">${eyebrow}</p><h2>${title}</h2></div>${text?`<p>${text}</p>`:''}</div>`;
const services=[
 {icon:'shield',title:'Trademark Registration',text:'Prepare and file your federal trademark application with a clear, guided process.',href:'trademark-registration.html'},
 {icon:'copyright',title:'Copyright Registration',text:'Document ownership of original creative work through federal copyright registration.',href:'copyright-registration.html'},
 {icon:'store',title:'Amazon Brand Registry',text:'Navigate brand enrollment and protection tools without sharing account credentials.',href:'amazon-brand-registry.html'}
];
const serviceCards=()=>`<div class="grid-3">${services.map(s=>`<article class="card service-card reveal"><div class="card-icon">${icon(s.icon)}</div><h3>${s.title}</h3><p>${s.text}</p><a class="btn-link" href="${s.href}">Explore service <span>→</span></a></article>`).join('')}</div>`;
const processSteps=()=>`<div class="process reveal"><article class="step"><h3>Complete the online application</h3><p>Share the essential details about your name, work, or brand through a straightforward questionnaire.</p></article><article class="step"><h3>We prepare your application</h3><p>Information is reviewed for completeness and relevant conflicts before the filing is prepared.</p></article><article class="step"><h3>Application filing</h3><p>After your review and approval, the completed application is filed with the appropriate federal office.</p></article></div>`;
const homePrices=[
 {name:'Basic',price:'39',text:'A straightforward way to begin your trademark registration.',features:['Standard processing time','Name search and business filing','Peace of mind check','Business consultation','Digital welcome kit','24/7 support','Business newsletter']},
 {name:'Professional',price:'99',text:'Priority preparation with additional founder resources.',features:['5-day priority notice','Name search and business filing','Peace of mind check','Business consultation','Digital welcome kit','24/7 lifetime support','Deluxe founder kit','Personalized notebook'],featured:true},
 {name:'Premium',price:'149',text:'Express preparation and expanded brand support.',features:['1–2 day express processing','Name search and business filing','Business consultation','Digital welcome kit','Expedited processing','Express shipping','Deluxe founder kit','Personalized notebook']}
];
const trademarkPrices=[
 {name:'Trademark Basic',price:'45',text:'Core search, preparation, and electronic delivery.',features:['USPTO database search for live and pending applications','Application preparation and filing with the USPTO','Electronic delivery of documents']},
 {name:'Trademark Standard',price:'99',text:'Basic package features plus practical ownership tools.',features:['Everything in Basic','Customizable cease and desist letter','Custom assignment template','Six months of post-filing monitoring'],featured:true},
 {name:'Trademark Deluxe',price:'199',text:'Extended monitoring and expedited preparation.',features:['Everything in Standard','One year of post-filing monitoring','24-business-hour application preparation']}
];
const priceGrid=(items,kind='trademark')=>`<div class="pricing-grid">${items.map(p=>`<article class="price-card reveal ${p.featured?'featured':''}">${p.featured?'<span class="recommended">Most selected</span>':''}<p class="eyebrow">${p.name}</p><p class="price"><sup>$</sup>${p.price}</p><p class="fee">Service fee<br>${kind==='copyright'?'+ applicable U.S. Copyright Office filing fee':'+ $350 USPTO base filing fee per class; additional fees may apply'}</p><p>${p.text}</p><ul class="features">${p.features.map(f=>`<li>${f}</li>`).join('')}</ul>${button('Choose '+p.name,{service:kind,package:p.name})}</article>`).join('')}</div>`;
const testimonials=[
 {title:'Professional and responsive',quote:'Mark Central Pro explains legal matters clearly and makes the process easier to navigate. The team was professional, responsive, and available when I had questions.',name:'Stacy Green'},
 {title:'Easy and effective',quote:'The registration process felt seamless. My application was handled quickly, and I always understood what came next.',name:'Graham Watts'},
 {title:'Remarkable customer service',quote:'The team provided thorough answers to my questions. The process was simple, responsive, and professionally managed.',name:'Jamie Lewis'}
];
const faqs=[
 ['What is a trademark?','A trademark can be a word, phrase, symbol, design, or combination that identifies the source of goods or services and distinguishes it from others.'],
 ['Why should I register my trademark?','Federal registration may strengthen your ability to protect a brand name, logo, slogan, or other source identifier and can provide important public notice of your claim.'],
 ['What is the difference between a trademark and copyright?','Trademarks generally identify the source of goods or services. Copyright protects original creative expression fixed in a tangible form.'],
 ['What can copyright registration cover?','Examples include visual art, photographs, musical compositions or lyrics, websites, motion pictures, scripts, screenplays, sound recordings, and other eligible original works.'],
 ['How long does the application process take?','Timing varies by application, filing office, and any issues raised during examination. Expedited service descriptions refer to Mark Central Pro preparation time, not government processing time.'],
 ['Are government filing fees included?','No. Displayed Mark Central Pro prices are service fees. Government filing fees are shown separately and may vary by filing type, number of classes, or other requirements.']
];
const faqBlock=(items=faqs,prefix='faq')=>`<div class="faq-list">${items.map((f,i)=>`<article class="faq-item"><h3><button class="faq-button" id="${prefix}-button-${i}" aria-expanded="false" aria-controls="${prefix}-${i}"><span>${f[0]}</span><span aria-hidden="true">+</span></button></h3><div class="faq-panel" id="${prefix}-${i}" role="region" aria-labelledby="${prefix}-button-${i}"><div><p>${f[1]}</p></div></div></article>`).join('')}</div>`;
const pageHero=(title,intro,crumb)=>`<section class="page-hero"><div class="container"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a><span>/</span>${crumb}</nav><p class="eyebrow">Mark Central Pro</p><h1>${title}</h1><p class="lead">${intro}</p></div></section>`;
const finalCta=(title='Protect what makes your brand yours.')=>`<section class="band"><div class="container band-inner"><div class="band-copy"><p class="band-kicker">Your next step</p><h2>${title}</h2><p class="band-text">Tell us what you’re building, and we’ll help you identify the right path to protection.</p></div>${button('Start your application')}</div></section>`;

const pages={
 'index.html':{title:'Trademark & Copyright Registration Services | Mark Central Pro',description:'Protect your business identity with guided trademark, copyright, and Amazon Brand Registry services from Mark Central Pro.',body:`
<section class="hero"><div class="hero-media"><picture><source srcset="assets/images/hero-brand-protection.avif" type="image/avif"><source srcset="assets/images/hero-brand-protection.webp" type="image/webp"><img src="assets/images/hero-brand-protection.png" width="1672" height="909" alt="Premium registration documents secured with a red ribbon" fetchpriority="high"></picture></div><div class="container"><div class="hero-content"><p class="eyebrow">Intellectual property services</p><h1>Protect the identity behind your ambition.</h1><p class="lead">Guided trademark, copyright, and Amazon Brand Registry services for founders and businesses ready to protect what they are building.</p><div class="actions">${button()}${button('Explore Services',{secondary:true,modal:false,href:'services.html',arrow:true})}</div><div class="hero-note"><span><i></i>Clear service pricing</span><span><i></i>Guided online process</span><span><i></i>Responsive support</span></div></div></div><div class="status-card"><div class="status-top"><span>APPLICATION PATH</span><span class="status-pill">Ready to begin</span></div><div class="status-row"><div class="status-icon">01</div><div><strong>Search & prepare</strong><br><small>Structured, guided review</small></div></div></div></section>
<section class="trust-strip" aria-label="Company highlights"><div class="container trust-grid"><div class="trust-item"><strong>100,000+</strong><span>Clients served</span></div><div class="trust-item"><strong>5-star</strong><span>Customer ratings</span></div><div class="trust-item"><strong>180+</strong><span>Countries served</span></div><div class="trust-item"><strong>3 steps</strong><span>Streamlined process</span></div></div></section>
<section class="section"><div class="container">${sectionHead('Services','One brand. Three ways to protect it.','Select the service that fits the asset you need to register or manage.')} ${serviceCards()}</div></section>
<section class="section surface"><div class="container">${sectionHead('The process','From first details to a prepared filing.','A clear sequence keeps you informed at every stage.')} ${processSteps()}</div></section>
<section class="section"><div class="container">${sectionHead('Trademark packages','Service levels built around your pace.','Government filing charges are always shown separately from our service fees.')} ${priceGrid(homePrices)}</div></section>
<section class="section dark"><div class="container split"><div><p class="eyebrow">Why Mark Central Pro</p><h2>Protection should feel considered—not complicated.</h2><p class="lead">A guided online experience, transparent separation of fees, and responsive support help you move forward with more clarity.</p>${button('Discuss your brand')}</div><div class="feature-list"><div class="feature-line"><b>01</b><div><h3>Worldwide perspective</h3><p>Support for business owners navigating brand protection from different markets.</p></div></div><div class="feature-line"><b>02</b><div><h3>Absolute transparency</h3><p>Service costs and government charges are presented separately.</p></div></div><div class="feature-line"><b>03</b><div><h3>Personalized support</h3><p>Questions are met with clear, human guidance throughout the process.</p></div></div></div></div></section>
<section class="section"><div class="container">${sectionHead('Client perspectives','Secured brands have confident owners.','Hear from business owners who trusted us with their registration journey.')}<div class="grid-3">${testimonials.map(t=>`<figure class="quote reveal"><blockquote>“${t.quote}”</blockquote><figcaption><strong>${t.title}</strong><cite>${t.name}</cite></figcaption></figure>`).join('')}</div></div></section>
<section class="section surface"><div class="container split"><div><p class="eyebrow">Questions, answered</p><h2>Know what happens before you begin.</h2><p class="lead">Straightforward answers about registration, fees, and the difference between protections.</p><a class="btn-link" href="faq.html">View every FAQ <span>→</span></a></div>${faqBlock(faqs.slice(0,4))}</div></section>${finalCta()}`},

 'about.html':{title:'About Mark Central Pro | Guided IP Registration',description:'Learn how Mark Central Pro guides businesses through trademark and copyright application preparation with clarity and support.',body:`${pageHero('Practical guidance for brands built to last.','We help founders and businesses navigate trademark and copyright application preparation through a clear online process.','About')}
<section class="section"><div class="container split"><div><p class="eyebrow">Our role</p><h2>Making complex registration feel more manageable.</h2><p class="lead">Brand names, original works, and other intellectual property represent serious investments of time and imagination. Mark Central Pro organizes the application journey so essential details are easier to understand, review, and move forward.</p><p>We support new ventures, established companies, and growing ecommerce brands. Our goal is to replace uncertainty with a coordinated, transparent experience.</p></div><aside class="editorial-panel"><p class="eyebrow">Our mission</p><h2 class="display">Give valuable ideas a clearer path to protection.</h2><p>Thoughtful preparation. Direct communication. No unnecessary friction.</p></aside></div></section>
<section class="section surface"><div class="container">${sectionHead('How we work','Expert attention, organized around you.')}<div class="grid-3"><article class="card"><div class="card-icon">${icon('search')}</div><h3>Knowledgeable guidance*</h3><p>Practical assistance throughout the preparation and filing process.</p></article><article class="card"><div class="card-icon">${icon('headset')}</div><h3>Personalized support*</h3><p>Reach out by phone or email when you need clarity on the next step.</p></article><article class="card"><div class="card-icon">${icon('shield')}</div><h3>Service-first philosophy*</h3><p>We work to resolve concerns professionally and keep the experience clear.</p></article></div></div></section>
<section class="section"><div class="container split"><div class="feature-list"><div class="feature-line"><b>01</b><div><h3>Tell us about your brand or work</h3><p>Complete a focused online questionnaire.</p></div></div><div class="feature-line"><b>02</b><div><h3>Review before filing</h3><p>Your information is organized for review and approval.</p></div></div><div class="feature-line"><b>03</b><div><h3>Stay informed</h3><p>Receive clear communication as the application moves forward.</p></div></div></div><div><p class="eyebrow">Why choose us</p><h2>Clarity at each decision point.</h2><p class="lead">We aim to make the registration cycle easier to follow while keeping you involved in the details that matter.</p>${button('Talk about your goals')}</div></div></section>${finalCta('Build your brand with protection in mind.')}`},

 'services.html':{title:'Trademark, Copyright & Brand Registry Services | Mark Central Pro',description:'Explore Mark Central Pro services for federal trademark registration, copyright registration, and Amazon Brand Registry support.',body:`${pageHero('A focused service for every kind of brand asset.','Explore guided application services designed around business identity, original creative work, and ecommerce brands.','Services')}
<section class="section"><div class="container">${sectionHead('Our services','Choose the protection your work calls for.','Each path starts with a focused application and clear next steps.')} ${serviceCards()}</div></section>
<section class="section surface"><div class="container">${sectionHead('A consistent path','How you start working with us.','The details vary by service; the experience remains simple.')} ${processSteps()}</div></section>
<section class="section"><div class="container split"><div class="editorial-panel"><p class="eyebrow">The difference</p><h2 class="display">Good protection starts with a well-prepared application.</h2><p>Organized information and thoughtful review help make the process easier to navigate.</p></div><div><p class="eyebrow">Built for clarity</p><h2>No confusing handoffs.</h2><div class="feature-list"><div class="feature-line"><b>✓</b><div><h3>Transparent fees</h3><p>Our service fees remain distinct from government charges.</p></div></div><div class="feature-line"><b>✓</b><div><h3>Review before filing</h3><p>You remain informed before an application moves forward.</p></div></div><div class="feature-line"><b>✓</b><div><h3>Human support</h3><p>Questions have a clear route to a responsive team.</p></div></div></div></div></div></section>${finalCta('Choose a service and take the next clear step.')}`},

 'trademark-registration.html':{title:'Trademark Registration Services | Mark Central Pro',description:'Search, prepare, and file a federal trademark application with transparent service pricing and guided support.',service:'Trademark Registration',body:`${pageHero('Turn your brand identity into an asset worth protecting.','Guided trademark application preparation for business names, logos, slogans, and other source identifiers.','Trademark Registration')}
<section class="trust-strip"><div class="container trust-grid"><div class="trust-item"><strong>Federal</strong><span>USPTO filing pathway</span></div><div class="trust-item"><strong>Clear</strong><span>Fee separation</span></div><div class="trust-item"><strong>Digital</strong><span>Online preparation</span></div><div class="trust-item"><strong>Guided</strong><span>Review and support</span></div></div></section>
<section class="section"><div class="container split"><div><p class="eyebrow">Why register</p><h2>A stronger foundation for the name customers recognize.</h2><p class="lead">Federal registration can help establish rights and public notice around a qualifying name, logo, slogan, or other trademark used with goods or services.</p><p>Registration does not remove every risk, but it can become an important part of protecting brand recognition and responding to potential infringement.</p></div><div class="editorial-panel"><p class="eyebrow">Registration benefits</p><ul class="features"><li>Support a claim of nationwide rights</li><li>Public notice of ownership</li><li>Federal registration record</li><li>A basis for certain enforcement options</li><li>Stronger brand-recognition foundation</li></ul></div></div></section>
<section class="section surface"><div class="container">${sectionHead('Application path','Three deliberate steps to a prepared filing.')} ${processSteps()}</div></section>
<section class="section"><div class="container">${sectionHead('Trademark packages','Choose your level of service.','The prices on this detail page are preserved from the source service page.')} ${priceGrid(trademarkPrices)}</div></section>
<section class="section dark"><div class="container split"><div><p class="eyebrow">Prepared with care</p><h2>Know the difference between preparation time and government review.</h2><p class="lead">Expedited packages concern our application-preparation timeline. USPTO review and registration timing remain outside our control.</p></div><div class="feature-list"><div class="feature-line"><b>01</b><div><h3>Search the federal database</h3><p>Review live and pending applications for relevant conflicts.</p></div></div><div class="feature-line"><b>02</b><div><h3>Confirm application details</h3><p>Review the prepared information before filing.</p></div></div><div class="feature-line"><b>03</b><div><h3>Receive documents electronically</h3><p>Keep essential application materials within reach.</p></div></div></div></div></section>
<section class="section"><div class="container">${sectionHead('Trademark FAQs','Questions before you begin.')} ${faqBlock(faqs.slice(0,5))}</div></section>${finalCta('Register your brand before confusion costs you momentum.')}`},

 'copyright-registration.html':{title:'Copyright Registration Services | Mark Central Pro',description:'Prepare and electronically file a federal copyright application for eligible original creative work.',service:'Copyright Registration',body:`${pageHero('Give original work a documented place in the record.','Prepare a federal copyright application for eligible creative work with a clear, guided online process.','Copyright Registration')}
<section class="section"><div class="container split"><div><p class="eyebrow">Copyright protection</p><h2>Your creative work deserves a clear ownership trail.</h2><p class="lead">Copyright can protect original expression fixed in a tangible form. Registration creates an official public record and may support important enforcement options.</p><p>You decide how your work is shared. We help organize the application details and prepare the filing pathway.</p></div><aside class="editorial-panel"><p class="eyebrow">Eligible work may include</p><h2 class="display">Art, images, words, music, film, and digital expression.</h2><p>Eligibility and filing requirements depend on the work and application.</p></aside></div></section>
<section class="section surface"><div class="container">${sectionHead('What can I copyright?','Original work takes many forms.')}<div class="grid-3">${['Works of art','Photos','Music or lyrics','Websites','Motion pictures','Scripts & screenplays'].map((x,i)=>`<article class="card reveal"><div class="card-icon">0${i+1}</div><h3>${x}</h3><p>Eligible original expression fixed in a tangible form.</p></article>`).join('')}</div></div></section>
<section class="section"><div class="container">${sectionHead('Copyright packages','Choose the preparation support you need.','U.S. Copyright Office filing charges are separate and vary by application.')} ${priceGrid([{name:'Copyright Basic',price:'99',text:'Professional preparation and federal electronic filing.',features:['Application preparation and review for common mistakes','Federal e-filing with the U.S. Copyright Office','Electronic application documentation']},{name:'Copyright Deluxe',price:'198',text:'Expanded documentation and faster preparation.',features:['Everything in Basic','Customizable cease and desist letter','Transfer and assignment template','24-hour preparation; normal Basic preparation is five business days'],featured:true}],'copyright')}</div></section>
<section class="section dark"><div class="container">${sectionHead('The process','Structured from creative work to application.')} ${processSteps()}</div></section>${finalCta('Put your original work on a clearer path to protection.')}`},

 'amazon-brand-registry.html':{title:'Amazon Brand Registry Support | Mark Central Pro',description:'Navigate Amazon Brand Registry enrollment and brand protection features without ever sharing your Amazon password.',service:'Amazon Brand Registry',body:`${pageHero('Build a stronger brand presence across Amazon.','Navigate Brand Registry enrollment, reporting, and protection tools with a safe, guided consultation.','Amazon Brand Registry')}
<section class="section"><div class="container split"><div><p class="eyebrow">Brand Registry</p><h2>More control over how your brand appears.</h2><p class="lead">Amazon Brand Registry offers enrolled brands tools to find and report potential infringement, improve product-page accuracy, and access brand-building features.</p><p>Eligibility and available features are controlled by Amazon and may vary by marketplace.</p></div><aside class="editorial-panel"><div class="card-icon">${icon('lock')}</div><h2 class="display">Your credentials stay yours.</h2><p>Mark Central Pro will never ask for your Amazon account password.</p></aside></div></section>
<section class="section surface"><div class="container">${sectionHead('Capabilities','Tools designed for proactive brand management.')}<div class="grid-3">${[['search','Bulk ASIN search','Review multiple ASINs or product URLs through a directed reporting workflow.'],['eye','Accurate brand representation','Help customers encounter the correct name, imagery, and information on product pages.'],['shield','Proactive protections','Use brand information to support detection of potentially harmful listings.'],['globe','Global search','Search for products across supported Amazon stores from a unified experience.'],['search','Image search','Find product listings that may use imagery similar to your products or logo.'],['store','Brand-building benefits','Access eligible tools such as Stores, Sponsored Brands, and brand dashboards.']].map(f=>`<article class="card reveal"><div class="card-icon">${icon(f[0])}</div><h3>${f[1]}</h3><p>${f[2]}</p></article>`).join('')}</div></div></section>
<section class="section"><div class="container">${sectionHead('Enrollment path','Prepare without handing over account access.')}<div class="process"><article class="step"><h3>Confirm your trademark status</h3><p>Identify the relevant trademark office, brand name, and application or registration details.</p></article><article class="step"><h3>Review eligibility</h3><p>Organize the non-sensitive information needed to understand your likely enrollment path.</p></article><article class="step"><h3>Continue securely</h3><p>Complete account-controlled steps directly within Amazon. Never share a password with us.</p></article></div></div></section>
<section class="section dark"><div class="container split"><div><p class="eyebrow">Safe consultation</p><h2>Tell us about the brand—not your login.</h2><p class="lead">Service charges vary by case and trademark application status. Begin with a consultation so the scope is clear.</p></div>${button('Request a safe consultation',{service:'Amazon Brand Registry'})}</div></section>${finalCta('Protect the consistency customers expect from your brand.')}`},

 'contact.html':{title:'Contact Mark Central Pro | Registration Support',description:'Contact Mark Central Pro by phone or email, or send an inquiry about our trademark, copyright, and brand registry services.',body:`${pageHero('Let’s make your next step clear.','Ask about a service, package, or application. Our support team is ready to help you choose the right path.','Contact')}
<section class="section"><div class="container split"><div><p class="eyebrow">Contact</p><h2>Speak with the support team.</h2><p class="lead">Questions are welcome. Contact us directly or send a message and tell us how we can help.</p><div class="feature-list"><div class="feature-line"><b>01</b><div><h3>Call</h3><p><a href="tel:+17545476430">${phone}</a><br>Monday–Friday, 9 a.m.–6 p.m. CT</p></div></div><div class="feature-line"><b>02</b><div><h3>Email</h3><p><a href="mailto:${email}">${email}</a></p></div></div><div class="feature-line"><b>03</b><div><h3>Responsive support</h3><p>Reach our team with questions about services, pricing, and next steps.</p></div></div></div></div>${contactForm()}</div></section>${finalCta('Your questions deserve a direct answer.')}`},

 'faq.html':{title:'Trademark & Copyright FAQs | Mark Central Pro',description:'Get straightforward answers about trademark registration, copyright registration, government fees, and application preparation.',faqs,body:`${pageHero('Clear answers before you commit.','Understand the core differences, likely costs, and application journey before selecting a service.','FAQ')}
<section class="section"><div class="container split"><div><p class="eyebrow">Trademark basics</p><h2>Start with the fundamentals.</h2><p class="lead">These answers provide general information and do not replace advice about your particular legal situation.</p></div>${faqBlock(faqs.slice(0,3),'trademark-faq')}</div></section>
<section class="section surface"><div class="container split"><div>${faqBlock(faqs.slice(3),'copyright-faq')}</div><div><p class="eyebrow">Copyright & fees</p><h2>Understand what is separate.</h2><p class="lead">Service fees cover Mark Central Pro preparation services. Government charges remain separate and may change.</p></div></div></section>${finalCta('Still unsure which service fits? Let’s talk.')}`},

 'privacy-policy.html':{title:'Privacy Policy | Mark Central Pro',description:'Read the Mark Central Pro privacy policy, including information collection, use, security, choices, and SMS terms.',legal:true,body:legalPage('Privacy Policy','Last updated September 8, 2026',[
 ['Information we collect',`<p>At Mark Central Pro, your privacy is of paramount importance to us. This Privacy Policy outlines how we collect, use, and protect personal information when you access or interact with our website.</p><h3>Personal information</h3><p>When you fill out forms or engage in activities on the website, we may collect information such as your name, email address, contact details, and other relevant data you voluntarily provide.</p><h3>Usage data</h3><p>We may collect information about how the website is accessed and used, including IP address, browser type, operating system, referring URLs, pages visited, and date and time of a visit.</p><h3>Cookies and tracking</h3><p>The website may use cookies or similar technologies to improve your experience, understand site usage, and support relevant communications.</p>`],
 ['How we use information','<p>Information may be used to provide and maintain services, respond to inquiries, monitor and improve website functionality, personalize the experience, and communicate service-related or promotional updates where permitted.</p>'],
 ['Sharing and disclosure','<p>We do not sell or rent personal information. Information may be disclosed to service providers that help operate the website, in response to legal requests or applicable law, or as part of a merger, acquisition, or sale of assets.</p>'],
 ['Security of information','<p>We take reasonable measures to protect information from unauthorized access, use, or disclosure. No method of internet transmission or electronic storage is completely secure, and absolute security cannot be guaranteed.</p>'],
 ['Your rights and choices','<p>You may request access to, correction of, or deletion of personal data. You may opt out of promotional communications and can control cookies through browser settings.</p>'],
 ["Children's privacy",'<p>The website is not intended for children under 13. We do not knowingly collect personal information from children under 13. Contact us if you believe a child has provided personal information.</p>'],
 ['SMS terms of service','<p>By voluntarily opting into SMS through a web form or other medium, you agree to receive messages from Mark Central Pro. Message frequency varies, and message and data rates may apply. You may opt out at any time by following the instructions in a message.</p>'],
 ['Changes and contact',`<p>We may update this policy by posting a revised version on this page. For questions about this policy or personal information, contact <a href="mailto:${email}">${email}</a>.</p>`]
 ])},

 'terms-of-service.html':{title:'Terms of Service | Mark Central Pro',description:'Review the terms governing use of the Mark Central Pro website and its trademark and copyright preparation services.',legal:true,body:legalPage('Terms of Service','Last updated September 8, 2026',[
 ['Agreement to terms','<p>These Terms of Service govern access to and use of the Mark Central Pro website and services. By using the website or ordering services, you acknowledge and agree to these terms and the Privacy Policy.</p>'],
 ['Nature of services','<p>Mark Central Pro provides document preparation and filing-related services described on the website. Government agencies make all decisions about examination, registration, and processing time. No particular result, approval, or registration date can be guaranteed.</p>'],
 ['Eligibility and acceptable use','<p>You must be legally capable of entering an agreement and may use the website only for lawful purposes. You may not interfere with website operation, attempt unauthorized access, introduce harmful code, misuse another person’s information, or use the services to infringe third-party rights.</p>'],
 ['Orders, payment, and electronic communications','<p>Orders are subject to acceptance, accurate customer information, and payment of applicable service and government fees. You consent to receive service-related records and communications electronically and are responsible for maintaining a working email address.</p>'],
 ['Accuracy and customer responsibilities','<p>You are responsible for providing complete and accurate information, reviewing prepared materials, responding promptly, and ensuring that your use of a name, mark, or work complies with applicable law. Delays or denials caused by incomplete information, government action, or circumstances outside our control are not guaranteed against.</p>'],
 ['Fees and government charges','<p>Mark Central Pro service fees are separate from government filing fees unless expressly stated otherwise. Government fees may depend on the number of classes, filing basis, application type, or later filings and may change without notice.</p>'],
 ['Disclaimers and limitation of liability','<p>The website and its content are provided on an “as is” and “as available” basis to the fullest extent permitted by law. General website content is informational and should not be treated as a guarantee of outcome. Limitations, exclusions, and remedies remain subject to applicable law.</p>'],
 ['Dispute resolution and arbitration','<p>To the fullest extent permitted by law, disputes arising from these terms, the website, or our services will be resolved through binding individual arbitration administered by the American Arbitration Association under its applicable rules and governed by the Federal Arbitration Act. Arbitration replaces a court or jury trial, and class, representative, joined, or consolidated actions are not permitted. You may opt out of this arbitration provision by emailing support@markcentralpro.com within 30 days of accepting these terms with the subject line “OPT-OUT,” your name and address, and a clear statement that you do not wish to resolve disputes through arbitration.</p>'],
 ['Intellectual property','<p>Mark Central Pro or its licensors retain rights in the website content, trademarks, graphics, software, and other protected materials. Limited personal use does not transfer ownership or grant a broader license.</p>'],
 ['User content and submissions','<p>You retain applicable rights in materials you submit but authorize the use, reproduction, and processing needed to provide the requested service. Do not submit content you do not have authority to use or content that violates another person’s rights.</p>'],
 ['Indemnification','<p>To the extent permitted by law, the source terms require users to indemnify and hold the company and relevant service providers harmless from claims arising from misuse of the website, inaccurate submissions, unlawful conduct, or violation of these terms or third-party rights.</p>'],
 ['Copyright notices','<p>Copyright infringement notices should identify the protected work, the allegedly infringing material, contact information, a good-faith statement, an accuracy and authority statement, and a physical or electronic signature. Send notices to support@markcentralpro.com with the subject “Copyright notice.”</p>'],
 ['Authorization','<p>By submitting an order, a customer may authorize Mark Central Pro to be listed as a recipient of correspondence related to a filing where applicable. Review the scope of any authorization before accepting services.</p>'],
 ['Refund policy','<p>Service and government fees are described by the source terms as non-refundable after the initial trademark search clearance report is conducted. Refund requests must be made before that work begins. If Mark Central Pro makes a filing error, the source policy states that it will work to correct the issue without an additional service charge.</p>'],
 ['Termination and availability','<p>Website access or services may be suspended or discontinued where permitted, including for misuse, nonpayment, legal requirements, or operational reasons. Provisions intended to survive termination continue to apply.</p>'],
 ['Miscellaneous','<p>If a provision is held invalid or unenforceable, the remaining provisions continue in effect. A failure to enforce a provision is not a waiver. Assignment, third-party beneficiary, and section-heading provisions remain subject to the complete approved agreement.</p>'],
 ['Changes and contact',`<p>Terms and service descriptions may be updated by posting changes to the website. Questions should be directed to <a href="mailto:${email}">${email}</a> or <a href="tel:+17545476430">${phone}</a>.</p>`]
 ])}
};

function contactForm(){return `<form class="form-card" data-validate novalidate><h2>Send us a message</h2><p>Share a few details below and our team will help you identify the right next step.</p><p class="form-status" role="status" tabindex="-1"></p><div class="error-summary" role="alert" tabindex="-1">Please correct the highlighted fields.</div><div class="field"><label for="contact-name">Your name</label><input id="contact-name" name="name" autocomplete="name" required><div class="field-error" id="contact-name-error"></div></div><div class="field"><label for="contact-email">Email address</label><input id="contact-email" name="email" type="email" autocomplete="email" required><div class="field-error" id="contact-email-error"></div></div><div class="field"><label for="contact-phone">Phone number</label><input id="contact-phone" name="phone" type="tel" autocomplete="tel"><div class="field-error" id="contact-phone-error"></div></div><div class="field"><label for="contact-message">How can we help?</label><textarea id="contact-message" name="message" required></textarea><div class="field-error" id="contact-message-error"></div></div><input type="hidden" name="source_page" value="contact"><button class="btn btn-primary" type="submit">Send inquiry</button></form>`}
function legalPage(title,notice,sections){return `${pageHero(title,'Review the information below to understand your rights, responsibilities, and use of Mark Central Pro services.',title)}<section class="section"><article class="legal"><p class="eyebrow">${notice}</p><nav class="legal-nav" aria-label="On this page"><strong>On this page</strong><ol>${sections.map((s,i)=>`<li><a href="#legal-${i}">${s[0]}</a></li>`).join('')}</ol></nav>${sections.map((s,i)=>`<section id="legal-${i}"><h2>${s[0]}</h2>${s[1]}</section>`).join('')}</article></section>`}

function header(active){const serviceActive=['trademark-registration.html','copyright-registration.html','amazon-brand-registry.html'].includes(active);return `<a class="skip-link" href="#main-content">Skip to main content</a><div class="utility"><div class="container"><a href="mailto:${email}">${email}</a><a href="tel:+17545476430">${phone}</a></div></div><header class="site-header"><div class="container nav-shell"><a class="brand" href="index.html" aria-label="Mark Central Pro home"><img src="assets/logo/mark-central-pro-logo.png" width="775" height="576" alt="Mark Central Pro"></a><nav class="nav" aria-label="Primary"><a class="${active==='index.html'?'active':''}" href="index.html">Home</a><a class="${active==='about.html'?'active':''}" href="about.html">About</a><div class="nav-drop"><button type="button" class="${active==='services.html'||serviceActive?'active':''}" aria-expanded="false" aria-controls="services-menu">Services <span class="nav-chevron" aria-hidden="true"></span></button><div class="dropdown" id="services-menu"><a href="services.html" class="${active==='services.html'?'active':''}">All services</a>${services.map(s=>`<a href="${s.href}" class="${active===s.href?'active':''}">${s.title}</a>`).join('')}</div></div><a class="${active==='contact.html'?'active':''}" href="contact.html">Contact</a><a class="${active==='faq.html'?'active':''}" href="faq.html">FAQ</a></nav>${button('Get Started')}<button id="menu-toggle" class="menu-toggle" aria-expanded="false" aria-controls="mobile-panel" aria-label="Open menu">☰</button></div></header><aside id="mobile-panel" class="mobile-panel" aria-hidden="true" aria-label="Mobile navigation"><button id="mobile-close" class="mobile-close" aria-label="Close menu">×</button><nav class="mobile-links"><a href="index.html">Home</a><a href="about.html">About</a><details class="mobile-services"><summary>Services</summary><a href="services.html">All services</a>${services.map(s=>`<a href="${s.href}">${s.title}</a>`).join('')}</details><a href="contact.html">Contact</a><a href="faq.html">FAQ</a></nav><div class="mobile-contact"><a href="tel:+17545476430">${phone}</a><a href="mailto:${email}">${email}</a></div>${button()}</aside>`}
function footer(){return `<footer class="site-footer"><div class="container footer-grid"><div class="footer-brand reveal"><img src="assets/logo/mark-central-pro-logo.png" width="360" height="176" alt="Mark Central Pro"><p>Guided trademark, copyright, and Amazon Brand Registry services for businesses protecting valuable ideas.</p></div><div class="footer-col reveal"><h3>Services</h3>${services.map(s=>`<a href="${s.href}">${s.title}</a>`).join('')}</div><div class="footer-col reveal"><h3>Company</h3><a href="about.html">About</a><a href="contact.html">Contact</a><a href="faq.html">FAQ</a></div><div class="footer-col reveal"><h3>Legal & contact</h3><a href="privacy-policy.html">Privacy Policy</a><a href="terms-of-service.html">Terms of Service</a><a href="mailto:${email}">${email}</a><a href="tel:+17545476430">${phone}</a></div></div><div class="container footer-bottom"><span>© <span data-year>2026</span> Mark Central Pro by Mark Consultant LLC. All rights reserved.</span></div></footer>`}
function modal(){return `<div class="modal" id="lead-modal" aria-hidden="true"><div class="modal-backdrop" data-modal-backdrop></div><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="lead-title"><div class="dialog-art"><p class="eyebrow">Start with confidence</p><h2 id="lead-title">Register your trademark and protect it from theft.</h2><p>Tell us about your business and the brand you want to protect. We’ll help you understand the next step.</p><div class="dialog-points" aria-hidden="true"><span>Clear pricing</span><span>Guided preparation</span><span>Responsive support</span></div></div><div class="dialog-main"><button class="modal-close" id="modal-close" aria-label="Close dialog">×</button><form class="dialog-form" id="lead-form" data-validate novalidate><p class="eyebrow">Get started</p><h2>Tell us about your brand.</h2><p class="form-status" role="status" tabindex="-1"></p><div class="error-summary" role="alert" tabindex="-1">Please correct the highlighted fields.</div><div class="form-row"><div class="field"><label for="lead-name">Your name</label><input id="lead-name" name="name" autocomplete="name" required><div class="field-error" id="lead-name-error"></div></div><div class="field"><label for="lead-email">Your email</label><input id="lead-email" name="email" type="email" autocomplete="email" required><div class="field-error" id="lead-email-error"></div></div></div><div class="field"><label for="lead-phone">Phone number</label><input id="lead-phone" name="phone" type="tel" autocomplete="tel" required><div class="field-error" id="lead-phone-error"></div></div><div class="field"><label for="lead-business">Brief description of your business</label><textarea id="lead-business" name="business_description" required></textarea><div class="field-error" id="lead-business-error"></div></div><label class="check"><input type="checkbox" name="marketing_consent" value="yes"><span>I would like to receive occasional newsletters, SMS updates, and offers. I can unsubscribe at any time. This choice is optional.</span></label><input type="hidden" name="source_page"><input type="hidden" name="selected_service"><input type="hidden" name="selected_package"><button class="btn btn-primary" type="submit">Submit request</button></form></div></section></div>`}
function schema(filename,page){const graph=[{'@type':'Organization','@id':`${siteUrl}/#organization`,name:'Mark Central Pro',url:`${siteUrl}/`,email,telephone:'+1-754-547-6430',logo:`${siteUrl}/assets/logo/mark-central-pro-logo.png`}];if(page.service)graph.push({'@type':'Service',name:page.service,provider:{'@id':`${siteUrl}/#organization`},url:`${siteUrl}/${filename}`});if(filename!=='index.html')graph.push({'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:`${siteUrl}/`},{'@type':'ListItem',position:2,name:page.service||page.title.split('|')[0].trim(),item:`${siteUrl}/${filename}`}]});if(page.faqs)graph.push({'@type':'FAQPage',mainEntity:page.faqs.map(f=>({'@type':'Question',name:f[0],acceptedAnswer:{'@type':'Answer',text:f[1]}}))});return JSON.stringify({'@context':'https://schema.org','@graph':graph}).replace(/</g,'\\u003c')}
function render(filename,page){const canonical=filename==='index.html'?`${siteUrl}/`:`${siteUrl}/${filename}`;return `<!doctype html><html lang="en" class="no-js"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${page.title}</title><meta name="description" content="${page.description}"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:site_name" content="Mark Central Pro"><meta property="og:title" content="${page.title}"><meta property="og:description" content="${page.description}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${siteUrl}/assets/images/social-preview.jpg"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${page.title}"><meta name="twitter:description" content="${page.description}"><meta name="twitter:image" content="${siteUrl}/assets/images/social-preview.jpg"><link rel="icon" href="assets/logo/favicon.png" type="image/png"><script>document.documentElement.classList.replace('no-js','js')</script><link rel="stylesheet" href="css/style.css"><script type="application/ld+json">${schema(filename,page)}</script><script defer src="js/main.js"></script></head><body>${header(filename)}<main id="main-content">${page.body}</main>${footer()}${modal()}</body></html>`}

for(const [filename,page] of Object.entries(pages))await writeFile(path.join(out,filename),render(filename,page),'utf8');
await writeFile(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${siteUrl}/sitemap.xml\n`);
await writeFile(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${Object.keys(pages).map(f=>`<url><loc>${f==='index.html'?siteUrl+'/':siteUrl+'/'+f}</loc></url>`).join('')}</urlset>`);
await writeFile(path.join(out,'.htaccess'),`Options -MultiViews\nRewriteEngine On\nRewriteRule ^about(?:\\.php)?/?$ /about.html [R=301,L]\nRewriteRule ^services(?:\\.php)?/?$ /services.html [R=301,L]\nRewriteRule ^contact(?:\\.php)?/?$ /contact.html [R=301,L]\nRewriteRule ^frequently-asked-question(?:\\.php)?/?$ /faq.html [R=301,L]\nRewriteRule ^trademark-registration-detail(?:\\.php)?/?$ /trademark-registration.html [R=301,L]\nRewriteRule ^copyright-registration-detail(?:\\.php)?/?$ /copyright-registration.html [R=301,L]\nRewriteRule ^amazon-brand-registry(?:\\.php)?/?$ /amazon-brand-registry.html [R=301,L]\nRewriteRule ^privacy-policy(?:\\.php)?/?$ /privacy-policy.html [R=301,L]\nRewriteRule ^terms-of-service(?:\\.php)?/?$ /terms-of-service.html [R=301,L]\n\n<IfModule mod_expires.c>\nExpiresActive On\nExpiresByType text/css "access plus 1 year"\nExpiresByType application/javascript "access plus 1 year"\nExpiresByType image/avif "access plus 1 year"\nExpiresByType image/webp "access plus 1 year"\nExpiresByType font/woff2 "access plus 1 year"\n</IfModule>\n`);
console.log(`Generated ${Object.keys(pages).length} pages in dist/`);
