import { chromium } from 'playwright-core';
import { mkdir, readdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const executablePath='C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe';
const browser=await chromium.launch({headless:true,executablePath});
const pages=(await readdir('.')).filter(file=>file.endsWith('.html'));
const sizes=process.argv.length>2?process.argv.slice(2).map(Number):[320,375,390,430,768,1024,1280,1440,1920];
const failures=[];

for(const width of sizes){
  const context=await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce'});
  const page=await context.newPage();
  for(const file of pages){
    const errors=[];
    page.removeAllListeners('pageerror');
    page.on('pageerror',error=>errors.push(error.message));
    await page.goto(`http://127.0.0.1:8000/${file}`,{waitUntil:'domcontentloaded'});
    const metrics=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,h1:document.querySelectorAll('h1').length}));
    if(metrics.scrollWidth>metrics.clientWidth+1)failures.push(`${file} at ${width}px overflows by ${metrics.scrollWidth-metrics.clientWidth}px`);
    if(metrics.h1!==1)failures.push(`${file} at ${width}px has ${metrics.h1} H1 elements`);
    if(file==='index.html'){
      const homeState=await page.evaluate(()=>({card:document.querySelectorAll('.status-card').length,stats:[...document.querySelectorAll('[data-count-to]')].map(el=>el.textContent),visible:document.querySelector('.stats-section')?.classList.contains('is-visible')}));
      if(homeState.card)failures.push(`Homepage status card remains at ${width}px`);
      if(homeState.visible||homeState.stats.join('|')!=='0|0|0|0')failures.push(`Reduced-motion counters did not wait for entrance at ${width}px: ${homeState.stats.join('|')}`);
      await page.evaluate(()=>document.querySelector('.stats-section').scrollIntoView({block:'center'}));
      await page.waitForTimeout(50);
      const reducedAfterEntrance=await page.evaluate(()=>[...document.querySelectorAll('[data-count-to]')].map(el=>({text:el.textContent,state:el.dataset.countState})));
      if(reducedAfterEntrance.some(counter=>counter.state!=='running')||reducedAfterEntrance.map(counter=>counter.text).join('|')==='100,000+|5-star|180+|3 steps')failures.push(`Reduced-motion counters bypassed count-up at ${width}px: ${reducedAfterEntrance.map(counter=>counter.text).join('|')}`);
    }
    if(errors.length)failures.push(`${file} at ${width}px console: ${errors.join('; ')}`);
  }
  await context.close();
}

const desktop=await browser.newContext({viewport:{width:1440,height:1080}});
const desktopPage=await desktop.newPage();
await desktopPage.goto('http://127.0.0.1:8000/index.html');
const counterStart=await desktopPage.evaluate(()=>[...document.querySelectorAll('[data-count-to]')].map(el=>({text:el.textContent,state:el.dataset.countState})));
if(counterStart.length!==4||counterStart.some(counter=>counter.state!=='waiting'||counter.text!=='0'))failures.push('Homepage counters did not initialize at literal zero');
await desktopPage.waitForTimeout(10000);
const counterAfterWait=await desktopPage.evaluate(()=>({scrollY:window.scrollY,stats:[...document.querySelectorAll('[data-count-to]')].map(el=>({text:el.textContent,state:el.dataset.countState}))}));
if(counterAfterWait.scrollY!==0||counterAfterWait.stats.some(counter=>counter.state!=='waiting'||counter.text!=='0'))failures.push('Homepage counters started without a user scroll');
await desktopPage.evaluate(()=>{window.__counterSamples=[...document.querySelectorAll('[data-count-to]')].map(el=>[el.textContent]);[...document.querySelectorAll('[data-count-to]')].forEach((el,index)=>new MutationObserver(()=>window.__counterSamples[index].push(el.textContent)).observe(el,{childList:true,characterData:true,subtree:true}))});
await desktopPage.evaluate(()=>window.scrollBy(0,1));
await desktopPage.waitForFunction(()=>[...document.querySelectorAll('[data-count-to]')].every(el=>el.dataset.countState==='running'));
const readAnimatedValues=()=>desktopPage.evaluate(()=>[...document.querySelectorAll('[data-count-to]')].map(el=>Number(el.textContent.replace(/\D/g,''))));
const timedSamples=[];
timedSamples.push({time:0,values:await readAnimatedValues()});
await desktopPage.waitForTimeout(1000);timedSamples.push({time:1,values:await readAnimatedValues()});
await desktopPage.waitForTimeout(1000);timedSamples.push({time:2,values:await readAnimatedValues()});
await desktopPage.waitForTimeout(500);timedSamples.push({time:2.5,values:await readAnimatedValues()});
await desktopPage.waitForTimeout(1500);timedSamples.push({time:4,values:await readAnimatedValues()});
const expectedRatios=[0,.2,.4,.5,.8];
timedSamples.forEach((sample,index)=>{for(const counterIndex of [0,2]){const target=counterIndex===0?100000:180;const ratio=sample.values[counterIndex]/target;if(Math.abs(ratio-expectedRatios[index])>.08)failures.push(`Counter ${counterIndex} was off linear pace at ${sample.time}s: ${sample.values[counterIndex]}`)}});
await desktopPage.waitForFunction(()=>[...document.querySelectorAll('[data-count-to]')].every(el=>el.dataset.countState==='complete'));
const counterFinal=await desktopPage.locator('[data-count-to]').allTextContents();
if(counterFinal.join('|')!=='100,000+|5-star|180+|3 steps')failures.push(`Homepage counters ended with incorrect values: ${counterFinal.join('|')}`);
const animationSamples=await desktopPage.evaluate(()=>window.__counterSamples.map(values=>[...new Set(values.map(value=>Number(value.replace(/\D/g,''))))]));
if(animationSamples[0].length<100||animationSamples[2].length<100)failures.push(`Large counters did not produce enough intermediate values: ${animationSamples[0].length}, ${animationSamples[2].length}`);
if(![0,1,2,3,4,5].every(value=>animationSamples[1].includes(value)))failures.push(`Rating counter skipped an integer stage: ${animationSamples[1].join(',')}`);
if(![0,1,2,3].every(value=>animationSamples[3].includes(value)))failures.push(`Steps counter skipped an integer stage: ${animationSamples[3].join(',')}`);
await desktopPage.evaluate(()=>window.scrollTo(0,document.documentElement.scrollHeight));
await desktopPage.waitForTimeout(150);
await desktopPage.evaluate(()=>document.querySelector('.trust-strip').scrollIntoView({block:'center'}));
await desktopPage.waitForTimeout(150);
const counterReturn=await desktopPage.evaluate(()=>[...document.querySelectorAll('[data-count-to]')].map(el=>({text:el.textContent,state:el.dataset.countState})));
if(counterReturn.some(counter=>counter.state!=='complete')||counterReturn.map(counter=>counter.text).join('|')!=='100,000+|5-star|180+|3 steps')failures.push('Homepage counters restarted after returning to the stats strip');
await desktopPage.reload({waitUntil:'domcontentloaded'});
const counterReload=await desktopPage.evaluate(()=>({scrollY:window.scrollY,stats:[...document.querySelectorAll('[data-count-to]')].map(el=>({text:el.textContent,state:el.dataset.countState}))}));
if(counterReload.stats.some(counter=>counter.state!=='waiting'||counter.text!=='0'))failures.push(`Homepage counters did not reset after reload at scrollY ${counterReload.scrollY}`);
const polish=await desktopPage.evaluate(()=>{const logo=document.querySelector('.footer-brand img');const caption=document.querySelector('.quote figcaption');return{logoFilter:getComputedStyle(logo).filter,logoWidth:logo.getBoundingClientRect().width,captionDirection:getComputedStyle(caption).flexDirection}});
if(polish.logoFilter!=='none'||polish.logoWidth<150)failures.push('Footer logo styling is not visible at desktop size');
if(polish.captionDirection!=='column')failures.push('Testimonial attribution is not stacked');
const animated=desktopPage.locator('.section-head').first();
await animated.scrollIntoViewIfNeeded();
await desktopPage.waitForTimeout(800);
if(Number(await animated.evaluate(el=>getComputedStyle(el).opacity))<.9)failures.push('Entrance animation did not reveal content');
await desktop.close();

const directionContext=await browser.newContext({viewport:{width:1440,height:700}});
const directionPage=await directionContext.newPage();
await directionPage.goto('http://127.0.0.1:8000/index.html');
await directionPage.evaluate(()=>window.scrollTo(0,40));
await directionPage.waitForTimeout(100);
await directionPage.evaluate(()=>window.scrollTo(0,20));
await directionPage.waitForTimeout(100);
const directionWaiting=await directionPage.evaluate(()=>({visible:document.querySelector('.stats-section').classList.contains('is-visible'),stats:[...document.querySelectorAll('[data-count-to]')].map(el=>el.textContent)}));
if(directionWaiting.visible||directionWaiting.stats.join('|')!=='0|0|0|0')failures.push('Stats entrance triggered before the section was reached or while scrolling upward');
await directionPage.evaluate(()=>window.scrollTo(0,100));
await directionPage.waitForFunction(()=>document.querySelector('.stats-section').classList.contains('is-visible'));
await directionContext.close();

const context=await browser.newContext({viewport:{width:390,height:850}});
const page=await context.newPage();
const formRequests=[];let formResponse='success';
await page.route('**/send-form.php',async route=>{const request=route.request();formRequests.push({method:request.method(),body:request.postData()||''});await new Promise(resolve=>setTimeout(resolve,150));if(formResponse==='success')await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({success:true,message:'Thank you. Your request has been sent successfully.'})});else await route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({success:false,message:'We could not send your request.'})})});
await page.goto('http://127.0.0.1:8000/index.html');
await page.click('#menu-toggle');
if(await page.getAttribute('#mobile-panel','aria-hidden')!=='false')failures.push('Mobile menu did not open');
await page.keyboard.press('Escape');
if(await page.getAttribute('#mobile-panel','aria-hidden')!=='true')failures.push('Mobile menu did not close with Escape');
await page.click('.hero [data-modal-trigger]');
if(await page.getAttribute('#lead-modal','aria-hidden')!=='false')failures.push('Lead modal did not open');
await page.fill('#lead-name','Test User');
await page.fill('#lead-email','test@example.com');
await page.fill('#lead-phone','+1 555 555 5555');
await page.fill('#lead-business','Accessibility and form validation check.');
await page.evaluate(()=>{const form=document.querySelector('#lead-form');form.requestSubmit();form.requestSubmit()});
await page.waitForFunction(()=>document.querySelector('#lead-form .form-status')?.classList.contains('success'));
const statusClass=await page.locator('#lead-form .form-status').getAttribute('class');
if(!statusClass.includes('show'))failures.push('Lead form success status did not appear');
if(formRequests.length!==1)failures.push(`Lead form submitted ${formRequests.length} times instead of once`);
const leadRequest=formRequests[0]||{method:'',body:''};
if(leadRequest.method!=='POST')failures.push('Lead form did not use POST');
for(const field of ['name="name"','name="email"','name="phone"','name="business_description"','name="form_source"','lead-modal','name="source_page"'])if(!leadRequest.body.includes(field))failures.push(`Lead request missing ${field}`);
if(await page.inputValue('#lead-name')!=='')failures.push('Lead form did not reset after successful delivery');
await page.click('[data-modal-backdrop]',{position:{x:5,y:5}});
if(await page.getAttribute('#lead-modal','aria-hidden')!=='true')failures.push('Lead modal did not close from backdrop');
formResponse='failure';
await page.goto('http://127.0.0.1:8000/contact.html');
await page.fill('#contact-name','Failure Test');
await page.fill('#contact-email','failure@example.com');
await page.fill('#contact-phone','+1 555 555 5555');
await page.fill('#contact-message','Keep this message after a delivery failure.');
await page.click('.form-card [type="submit"]');
await page.waitForFunction(()=>document.querySelector('.form-card .form-status')?.classList.contains('show'));
if(formRequests.length!==2)failures.push(`Expected two total form requests, received ${formRequests.length}`);
const contactRequest=formRequests[1]||{method:'',body:''};
for(const field of ['name="name"','name="email"','name="phone"','name="message"','name="form_source"','contact-page','name="source_page"'])if(!contactRequest.body.includes(field))failures.push(`Contact request missing ${field}`);
if(await page.inputValue('#contact-message')!=='Keep this message after a delivery failure.')failures.push('Contact form values were not preserved after failure');
await page.goto('http://127.0.0.1:8000/faq.html');
await page.click('.faq-button');
if(await page.getAttribute('.faq-button','aria-expanded')!=='true')failures.push('FAQ did not expand');
await page.waitForTimeout(350);
if(await page.locator('.faq-panel').first().evaluate(el=>el.getBoundingClientRect().height)<20)failures.push('FAQ answer panel remained collapsed');
await page.goto(pathToFileURL(resolve('faq.html')).href);
await page.click('.faq-button');
if(await page.getAttribute('.faq-button','aria-expanded')!=='true')failures.push('FAQ did not expand from a local file');
await page.waitForTimeout(350);
if(await page.locator('.faq-panel').first().evaluate(el=>el.getBoundingClientRect().height)<20)failures.push('FAQ answer panel remained collapsed from a local file');
await context.close();
await browser.close();

await mkdir('reports',{recursive:true});
const result=failures.length?failures.join('\n'):`Visual and interaction checks passed for ${pages.length} pages at ${sizes.join(', ')}px.`;
await writeFile(`reports/visual-check-${sizes.join('-')}.txt`,result);
if(failures.length){console.error(result);process.exit(1)}
console.log(result);
